name: eduquest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dash_chat_2: ^0.0.21
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.3
  gemini: ^2.1.1
  google_generative_ai: ^0.4.6
  google_ml_kit: ^0.19.0
  google_mlkit_text_recognition: ^0.14.0
  google_nav_bar: ^5.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  open_file: ^3.5.9
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
